### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by TCH68k** [YunzheZJU/youtube-po-token-generator#10]
Hello,

I tried to do a test run:
`node ./one-shot.js`
```
/media/UTILDISK/youtube-po-token-generator/lib/task.js:12
    stop: () => destroy?.(),
                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/media/UTILDISK/youtube-po-token-generator/index.js:1:24)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
NodeJS version is 12.22.12. Too old? What is the minimum required NodeJS?

**Comment by YunzheZJU** [comment]
The Minimum required Node version is 18.0, as noted in package.json.

**Comment by TCH68k** [comment]
Thank you, then i need to update it somehow.
