### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory when trying to run `one-shot.js`

### ISSUE THREAD

**Issue by deepaerial** [YunzheZJU/youtube-po-token-generator#3]
When trying to run `one-shot.js` file from `examples` folder I get following error:
```

<--- Last few GCs --->

[68402:0x7fba84200000]    98314 ms: Mark-Compact 4038.0 (4144.9) -> 4025.8 (4141.9) MB, 1518.83 / 0.01 ms  (average mu = 0.508, current mu = 0.241) allocation failure; GC in old space requested
[68402:0x7fba84200000]   101303 ms: Mark-Compact 4035.5 (4143.9) -> 4030.9 (4145.4) MB, 2642.13 / 0.01 ms  (average mu = 0.308, current mu = 0.116) allocation failure; GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0x106bfece0 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
 2: 0x106db626c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
 3: 0x106fa6007 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
 4: 0x106fa4869 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
 5: 0x106f990d1 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
 6: 0x106f99b15 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
 7: 0x106f7b46c v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
 8: 0x106f6f4ab v8::internal::FactoryBase<v8::internal::Factory>::NewBytecodeArray(int, unsigned char const*, int, int, v8::internal::Handle<v8::internal::FixedArray>) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
 9: 0x10709e68c v8::internal::Handle<v8::internal::BytecodeArray> v8::internal::interpreter::BytecodeArrayWriter::ToBytecodeArray<v8::internal::Isolate>(v8::internal::Isolate*, int, int, v8::internal::Handle<v8::internal::ByteArray>) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
10: 0x1070a0d95 v8::internal::Handle<v8::internal::BytecodeArray> v8::internal::interpreter::BytecodeGenerator::FinalizeBytecode<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Script>) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
11: 0x1070c55b5 v8::internal::CompilationJob::Status v8::internal::interpreter::InterpreterCompilationJob::DoFinalizeJobImpl<v8::internal::Isolate>(v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Isolate*) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
12: 0x1070c542c v8::internal::interpreter::InterpreterCompilationJob::FinalizeJobImpl(v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Isolate*) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
13: 0x106e7a53d v8::internal::CompilationJob::Status v8::internal::(anonymous namespace)::FinalizeSingleUnoptimizedCompilationJob<v8::internal::Isolate>(v8::internal::UnoptimizedCompilationJob*, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Isolate*, std::__1::vector<v8::internal::FinalizeUnoptimizedCompilationData, std::__1::allocator<v8::internal::FinalizeUnoptimizedCompilationData>>*) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
14: 0x106e730c5 bool v8::internal::(anonymous namespace)::IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Script>, v8::internal::ParseInfo*, v8::internal::AccountingAllocator*, v8::internal::IsCompiledScope*, std::__1::vector<v8::internal::FinalizeUnoptimizedCompilationData, std::__1::allocator<v8::internal::FinalizeUnoptimizedCompilationData>>*, std::__1::vector<v8::internal::DeferredFinalizationJobData, std::__1::allocator<v8::internal::DeferredFinalizationJobData>>*) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
15: 0x106e72ba4 v8::internal::Compiler::Compile(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Compiler::ClearExceptionFlag, v8::internal::IsCompiledScope*, v8::internal::CreateSourcePositions) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
16: 0x106e73558 v8::internal::Compiler::Compile(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag, v8::internal::IsCompiledScope*) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
17: 0x1073f0b66 v8::internal::Runtime_CompileLazy(int, unsigned long*, v8::internal::Isolate*) [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
18: 0x1077cadb6 Builtins_CEntry_Return1_ArgvOnStack_NoBuiltinExit [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
19: 0x10773dba4 Builtins_CompileLazy [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
20: 0x10773c79c Builtins_InterpreterEntryTrampoline [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
21: 0x10773c79c Builtins_InterpreterEntryTrampoline [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
22: 0x10773c79c Builtins_InterpreterEntryTrampoline [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
23: 0x10773c79c Builtins_InterpreterEntryTrampoline [/Users/myuser/.nvm/versions/node/v20.14.0/bin/node]
[1]    68402 abort      node one-shot.js
```
Node version: `v20.14.0`

**Comment by YunzheZJU** [comment]
This seems to be an issue of the env you are using to execute the javascript code.

Have you tryied running node with `NODE_OPTIONS=--max_old_space_size=4096`? This should raise the heap limit to avoid this kind of error.

https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory

**Comment by s123121** [comment]
I am pretty sure this got into the endless loop of calling while to generate the poToken, it can not generate the valid poTken -> memory leak

**Comment by YunzheZJU** [comment]
I have switched to `node-v20.14.0-darwin-arm64` and manually run the endless loop in https://github.com/YunzheZJU/youtube-po-token-generator/blob/main/lib/task.js.

The program does not crash even if it has looped for 200+ times. 

Strangely it would output extra long poTokens in the 62th, 123th and 182th loop, which causes a long wait before the 63th, 124th, and 183th one is generated.

The memory usage of node keeps around 1.0GB ~ 1.2GB after some loops, while it was 500+ MB in the beginning.

However, when I switch to node 20.1.0, that decreases from >500MB to <200MB and never reached 300MB even if 200 loops is run.

So I thick that there should be no memory leak caused by myself (at least before 200 loops are reached) but there is a chance that logics from youtube's code may introduce memory leaks when it cannot generate the valid token.

And the node version may affect the memory usage, as you can see, so switching node versions may do some help.

**Comment by TCH68k** [comment]
I tried it with the following nodejs versions: 18.20.5, 19.9.0, 20.18.1, 21.7.3, 22.12.0, 23.5.0
With `NODE_OPTIONS=--max_old_space_size=4096`. The result was all the same: this error message.

**Comment by YunzheZJU** [comment]
> I tried it with the following nodejs versions: 18.20.5, 19.9.0, 20.18.1, 21.7.3, 22.12.0, 23.5.0 With `NODE_OPTIONS=--max_old_space_size=4096`. The result was all the same: this error message.

Are you running with the fresh data from youtube, e.g the `one-shot.js` or `generate`, or running with your own 'visitorData' (using `createTask` directly)?

Then I think maybe there is something polluted in the data fetched from youtube.

**Comment by TCH68k** [comment]
I have no idea. I just did as told: `nodejs ./one-shot.js`

**Comment by TCH68k** [comment]
I've installed the latest `nodejs` and `jsdom` and fetched the latest of your source. Then tried to do `nodejs ./one-shot.js`:
```
/media/UTILDISK/potoken/youtube-po-token-generator/lib/task.js:12
    stop: () => destroy?.(),
                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/media/UTILDISK/potoken/youtube-po-token-generator/index.js:1:24)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by YunzheZJU** [comment]
Try `node -v` and ensure the printed version number is >= 18.0

> I've installed the latest `nodejs` and `jsdom` and fetched the latest of your source. Then tried to do `nodejs ./one-shot.js`:
> 
> ```
> /media/UTILDISK/potoken/youtube-po-token-generator/lib/task.js:12
>     stop: () => destroy?.(),
>                         ^
> 
> SyntaxError: Unexpected token '.'
>     at wrapSafe (internal/modules/cjs/loader.js:915:16)
>     at Module._compile (internal/modules/cjs/loader.js:963:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>     at Module.require (internal/modules/cjs/loader.js:887:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/media/UTILDISK/potoken/youtube-po-token-generator/index.js:1:24)
>     at Module._compile (internal/modules/cjs/loader.js:999:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> ```

**Comment by TCH68k** [comment]
```
root@Csabi:~
# node -v
v23.6.1
```
I installed the latest.

**Comment by YunzheZJU** [comment]
> ```
> root@Csabi:~
> # node -v
> v23.6.1
> ```
> 
> I installed the latest.

I found that you have mentioned `nodejs ./one-shot.js` instead of `node ./one-shot.js` several times. Is that just a typo?

Anyway, node v23 should recognize the `?.` correctly.

Would you please try issuing these commands and check the result? 

```bash
npm install -g youtube-po-token-generator

youtube-po-token-generator
```

**Comment by TCH68k** [comment]
No, that was not a typo, i did not know that there is a difference and thought that `nodejs` and `node` are the same. Thanks for pointing out. However, when i did `node ./one-shot.js`, after several minutes of waiting with CPU loads up in the sky, the following error was the result:
```
<--- Last few GCs --->

[11456:0x87f2000]   127822 ms: Scavenge (reduce) (interleaved) 4066.7 (4104.2) -> 4062.6 (4093.4) MB, pooled: 0 MB, 20.17 / 0.01 ms  (average mu = 0.100, current mu = 0.030) allocation failure;
[11456:0x87f2000]   129802 ms: Mark-Compact (reduce) 4062.8 (4093.4) -> 4061.5 (4088.7) MB, pooled: 0 MB, 1966.41 / 0.00 ms  (+ 276.3 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2399 ms) (average mu = 0.142,

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0xebe335 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [node]
 2: 0x1329df0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 3: 0x132a18c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 4: 0x158d0c5  [node]
 5: 0x158d0f2  [node]
 6: 0x159feaa  [node]
 7: 0x15a3ea0  [node]
 8: 0x2002ba1  [node]
Félbeszakítva
```
(_"Félbeszakítva"_ is "interrupted" in hungarian.)

Next, i did what you've suggested: i installed and executed `youtube-po-token-generator`. Again, after minutes of high CPU load, i got this result:
```
(node:16843) [DEP0040] DeprecationWarning: The `punycode` module is deprecated.                                                                                                                                                            Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

<--- Last few GCs --->

[16843:0x747a000]   133960 ms: Mark-Compact (reduce) 4070.8 (4094.5) -> 4067.7 (4092.2) MB, pooled: 0 MB, 715.60 / 0.00 ms  (+ 1411.4 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2799 ms) (average mu = 0.227, [16843:0x747a000]   136669 ms: Mark-Compact (reduce) 4073.6 (4096.7) -> 4069.5 (4096.0) MB, pooled: 0 MB, 2253.46 / 0.00 ms  (+ 40.4 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2308 ms) (average mu = 0.192, c

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0xebe335 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [node]
 2: 0x1329df0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 3: 0x132a18c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 4: 0x158d0c5  [node]
 5: 0x158d0f2  [node]
 6: 0x159feaa  [node]
 7: 0x15a3ea0  [node]
 8: 0x2002ba1  [node]
Félbeszakítva
```

**Comment by DeAJota** [comment]
I have the same issue. I'm working with the last node version and after a while appears that message

**Comment by lealexio** [comment]
Same issue, i try with 12gb and with node 18 & last version :

```
C:\Users\alexl>node --max-old-space-size=12288 "%APPDATA%\npm\node_modules\youtube-po-token-generator\bin\cli.mjs"

<--- Last few GCs --->

[6336:000002253FCD83C0]   512404 ms: Mark-sweep (reduce) 12073.6 (12335.1) -> 12071.7 (12335.4) MB, 6470.7 / 0.0 ms  (average mu = 0.316, current mu = 0.368) allocation failure; scavenge might not succeed
[6336:000002253FCD83C0]   519294 ms: Mark-sweep (reduce) 12073.1 (12335.6) -> 12071.9 (12335.6) MB, 6876.2 / 0.0 ms  (average mu = 0.176, current mu = 0.002) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF694B81ADF node_api_throw_syntax_error+203775
 2: 00007FF694B014B6 SSL_get_quiet_shutdown+63558
 3: 00007FF694B02822 SSL_get_quiet_shutdown+68530
 4: 00007FF6955A2F34 v8::Isolate::ReportExternalAllocationLimitReached+116
 5: 00007FF69558E2A2 v8::Isolate::Exit+674
 6: 00007FF6954102FC v8::internal::EmbedderStackStateScope::ExplicitScopeForTesting+124
 7: 00007FF69541D5DD v8::internal::Heap::PublishPendingAllocations+1117
 8: 00007FF69541A667 v8::internal::Heap::PageFlagsAreConsistent+3367
 9: 00007FF69540CD97 v8::internal::Heap::CollectGarbage+2039
10: 00007FF695423753 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath+2099
11: 00007FF695423FFD v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath+93
12: 00007FF695433833 v8::internal::Factory::NewFillerObject+851
13: 00007FF695124F65 v8::internal::DateCache::Weekday+1349
14: 00007FF6956405C1 v8::internal::SetupIsolateDelegate::SetupHeap+558193
15: 00007FF695641574 v8::internal::SetupIsolateDelegate::SetupHeap+562212
16: 00007FF615F852F7
```

**Comment by makarasty** [comment]
In my environment (Windows 10), the solution only functioned correctly within PowerShell. I also used the Bun runtime, but I doubt that's a significant factor

<img width="2241" height="1278" alt="Image" src="https://github.com/user-attachments/assets/4dde424d-6c28-405b-b9f6-d8f07fc453d3" />

I didn't put much effort into the photo, sorry about that.
