### ISSUE TITLE
[BUG] TypeError: Cannot set prototype of immutable prototype object

### ISSUE THREAD

**Issue by hnuuhc** [YunzheZJU/youtube-po-token-generator#6]
my code:

```ts
import { createTask } from 'youtube-po-token-generator/lib/task'
import { Youtube } from './sdk'

var link = 'https://www.youtube.com/watch?v=qjbj7xWOSKQ'

var youtube = new Youtube({ proxy: ':7890' })
var player = await youtube.player(link)

console.log(player.responseContext.visitorData)

const visitorData = player.responseContext.visitorData

createTask(visitorData).then((task: any) => task.start).then(console.log, console.error)
```

result: 

```
CgsxUEQ2bGRoYnlPayjdzd24BjIKCgJKUBIEGgAgaQ%3D%3D
[AsyncFunction: start]
```

change:

```
createTask(visitorData).then((task: any) => task.start).then(console.log, console.error)
```

to:

```
createTask(visitorData).then((task: any) => task.start()).then(console.log, console.error)
```

then result: 

```
169 |   });
170 |
171 |   WindowConstructor.prototype = windowPrototype;
172 |   Object.setPrototypeOf(window, windowPrototype);
173 |   if (makeVMContext) {
174 |     Object.setPrototypeOf(window._globalProxy, windowPrototype);
                 ^
TypeError: Cannot set prototype of immutable prototype object
      at F:\Project\NodeScript\node_modules\jsdom\lib\jsdom\browser\Window.js:174:12
      at new JSDOM (F:\Project\NodeScript\node_modules\jsdom\lib\api.js:36:20)
      at F:\Project\NodeScript\node_modules\youtube-po-token-generator\lib\task.js:16:30
      at F:\Project\NodeScript\node_modules\youtube-po-token-generator\lib\task.js:15:59
      at new Promise (1:11)
      at F:\Project\NodeScript\node_modules\youtube-po-token-generator\lib\task.js:15:35
      at start (F:\Project\NodeScript\node_modules\youtube-po-token-generator\lib\task.js:13:24)
```

version: ^0.2.0

Then, we want to add `export` for `TypeScript` compatibility

**Comment by YunzheZJU** [comment]
Thank your for your report. It seems to be an error originates from `jsdom`.

What is your node version?

Is it possible to run your code in WSL to avoid this error?

For Typescript support, what is your expectation? Would a simple `index.d.ts` including the type annotation for `createTask` be enough?

**Comment by YunzheZJU** [comment]
I'm sorry that only NodeJS is supported and tested.

BunJS is a quite new runtime for javascript and perhaps there exists some compatibility issue between BunJS and `jsdom` we are using.

I believe it is hard for BunJS to run the samples provided by [`jsdom`](https://www.npmjs.com/package/jsdom).

**Comment by YunzheZJU** [comment]
Type declarations have been added and I hope they would work for you.
